/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DonationsBox: typeof import('./src/components/DonationsBox.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    ReviewCard: typeof import('./src/components/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeeklyCardItem: typeof import('./src/components/WeeklyCardItem.vue')['default']
  }
}
